### ISSUE TITLE
js.jar missing

### ISSUE THREAD

**Issue by sreid99** [Comcast/css_lint_ruby#1]
Hi,

I'm getting "Unable to access jarfile /Users/sandyreid/.rvm/gems/ruby-1.9.2-p320/gems/css_lint-0.9.10.0/lib/vendor/js.jar" when I use version 0.9.10.0. 

The file seems to be missing.

Version 0.9.9.1 works ok.

**Comment by JohnRiv** [comment]
Whoops, thanks for pointing that out. This is now fixed in 0.9.10.1
